### PR TITLE
Added runtest script ieee-adds, test of IEEE Add instructions

### PR DESCRIPTION
**Pull request by srorso**
Tests all forms of the Binary Floating Point ADD instruction.  Also tests 32-bit Integer versions of the CONVERT FROM FIXED and CONVERT TO FIXED instructions.  Tests 11 Binary Floating Point instructions and five Floating Point Support instructions.

### CODE REVIEW

**Comment by Fish-Git** [comment]
Sorry for the scare. :)

This was the first time I've ever made a "line comment" in GitHub.

Also, a _completely unrelated_ FYI regarding GitHub (in case you care): Try to keep your commit comments short and sweet to prevent the "..." ellipsis from appearing. If you need to go into further details, add a blank line after your primary commit comment and then describe further details using as many lines as you need (but try not to write a book of course!).

See my "SCSI tape fixes:" commit made yesterday:

* [https://github.com/hercules-390/hyperion/commits](https://github.com/hercules-390/hyperion/commits)

Clicking on the ellipsis expands the commit message so you can see additional details.

But the primary commit message should be relatively short and sweet.

Yes, I can be anal at times. &nbsp;`:)`

**Comment by Fish-Git** [comment]
(Oops!) NEVER MIND! It looks like you already know that! Sorry!

**Comment by srorso** [comment]
> On May 18, 2016, at 2:43 PM, Fish-Git <notifications@github.com> wrote:
> 
> (Oops!) NEVER MIND! It looks like you already know that! Sorry!
> 

Not really as it turn out.  I agree with the desirability of the result you suggest, and now I know how to achieve it other than by accident. 

Thanks!

Best regards,
Steve Orso

+1 610 217 7050

**Comment by srorso** [comment]
> On May 18, 2016, at 2:41 PM, Fish-Git <notifications@github.com> wrote:
> This was the first time I've ever made a "line comment" in GitHub.
> 

I have wondered as well how that would work.  I was unimpressed with the context Github provided in the e-mail (the line content would have been nice). But the web presentation of the comment was excellent.  
> Yes, I can be anal at times.  :)
> 
Also known as observant and detail-oriented, respectable traits often associated with skilled programmers and diagnosticians.  

Best Regards, 
Steve Orso

+1 610 217 7050

**Pull request merged**
